### ISSUE TITLE
How to use ScriptCacheDump Project

### ISSUE THREAD

**Issue by Graphicscore** [gibbed/Gibbed.RED4#3]
Where do I find or how do I create the script cache and/or final.redscript file that are used in the code of the Project ?
Would like to poke around in the scripts myself but just getting into not, not much information available yet :)

**Comment by gibbed** [comment]
You can see example code on modifying `final.redscripts` in the `ScriptCachePatchTest` project. As for the `final.redscripts` file, it's in `r6\cache` directory of the game files.
